In [2]:
import pandas as pd

df = pd.read_csv("../data/sample_report.csv")

df

       Site  Device    Month  Consumption_kWh  COP  Alarms
0  Helsinki  Pump A  2026-05             1200  3.5       2
1  Helsinki  Pump A  2026-06             1450  2.1       4
2     Espoo  Pump B  2026-05              950  3.8       1
3     Espoo  Pump B  2026-06              980  3.7       1
4    Vantaa  Pump C  2026-05             2200  3.2      10
5    Vantaa  Pump C  2026-06             2700  2.8       6
6     Turku  Pump D  2026-05             1500  3.6       0
7     Turku  Pump D  2026-06             1520  3.5       1

In [3]:
may = df[df["Month"] == "2026-05"]
print(may)

       Site  Device    Month  Consumption_kWh  COP  Alarms
0  Helsinki  Pump A  2026-05             1200  3.5       2
2     Espoo  Pump B  2026-05              950  3.8       1
4    Vantaa  Pump C  2026-05             2200  3.2      10
6     Turku  Pump D  2026-05             1500  3.6       0

In [4]:
df.groupby("Month")["Consumption_kWh"].sum()

Month
2026-05    5850
2026-06    6650
Name: Consumption_kWh, dtype: int64

In [5]:
may = df[df["Month"] == "2026-05"]
june = df[df["Month"] == "2026-06"]

comparison = may.merge(
    june,
    on="Device",
    suffixes=("_may", "_june")
    )

delta_cop=comparison["cop_change"] = (
        comparison["COP_june"]
        - comparison["COP_may"]
    )
delta_alarms=comparison["alarms_diff"] = (
        comparison["Alarms_june"]
        - comparison["Alarms_may"]
    )
comparison[abs(delta_cop) > 1]
comparison[(delta_alarms) > 5]

Empty DataFrame
Columns: [Site_may, Device, Month_may, Consumption_kWh_may, COP_may, Alarms_may, Site_june, Month_june, Consumption_kWh_june, COP_june, Alarms_june, cop_change, alarms_diff]
Index: []

In [6]:
cop_anomalies = comparison[abs(delta_cop) > 0.3]
cop_anomalies

,Site_may,Device,Month_may,Consumption_kWh_may,COP_may,Alarms_may,Site_june,Month_june,Consumption_kWh_june,COP_june,Alarms_june,cop_change,alarms_diff
0,Helsinki,Pump A,2026-05,1200,3.5,2,Helsinki,2026-06,1450,2.1,4,-1.4,2
2,Vantaa,Pump C,2026-05,2200,3.2,10,Vantaa,2026-06,2700,2.8,6,-0.4,-4

In [7]:
cop_anomalies["Device"][0]

'Pump A'

In [9]:
comparison[["Device", "COP_may", "COP_june", "cop_change", "Alarms_may", "Alarms_june", "alarms_diff"]]

   Device  COP_may  COP_june  cop_change  Alarms_may  Alarms_june  alarms_diff
0  Pump A      3.5       3.1        -0.4           2            4            2
1  Pump B      3.8       3.7        -0.1           1            1            0
2  Pump C      3.2       2.8        -0.4           3            6            3
3  Pump D      3.6       3.5        -0.1           0            1            1

In [8]:
comparison[[
    "Device",
    "Alarms_may",
    "Alarms_june",
    "alarms_diff"
]]

   Device  Alarms_may  Alarms_june  alarms_diff
0  Pump A           2            4            2
1  Pump B           1            1            0
2  Pump C          10            6           -4
3  Pump D           0            1            1